name: Fast Multi-Tomcat Monitor

on:
#   schedule:
#     - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Initialize
        run: "mkdir -p logs && echo '⏱ Monitor Start: $(date)' > logs/monitor.log"

      - name: Check Tomcat URLs in Parallel
        run: |
          urls=(
            "https://mglapp1.mahanagargas.com:8443/"
            "https://mglapp2.mahanagargas.com:8443/"
            "https://mglapp3.mahanagargas.com:8443/"
          )

          check_url() {
            url=$1
            status=$(curl -s -o /dev/null -w "%{http_code}" "$url")
            timestamp=$(date '+%Y-%m-%d %H:%M:%S')
            
            if [ "$status" != "200" ]; then
              echo "❌ [$timestamp] DOWN - $url (Status: $status)" >> logs/monitor.log

              # echo -e "Subject: ALERT: Tomcat Down\n\nTomcat at $url is NOT reachable.\nStatus: $status\nTime: $timestamp" \
              # | msmtp --host=smtp.sendgrid.net \
              #         --port=587 \
              #         --auth=on \
              #         --user="$SMTP_USER" \
              #         --password="$SMTP_PASS" \
              #         --tls=on \
              #         --from="Tomcat Monitor <alert@yourdomain.com>" \
              #         "$ALERT_EMAIL"
            else
              echo "✅ [$timestamp] UP   - $url (Status: $status)" >> logs/monitor.log
            fi
          }

          export -f check_url
          printf "%s\n" "${urls[@]}" | xargs -n1 -P4 -I{} bash -c 'check_url "$@"' _ {}

        # env:
        #   SMTP_USER: ${{ secrets.SMTP_USER }}
        #   SMTP_PASS: ${{ secrets.SMTP_PASS }}
        #   ALERT_EMAIL: ${{ secrets.ALERT_EMAIL }}

      - name: Upload Monitor Log
        uses: actions/upload-artifact@v4
        with:
          name: monitor-logs
          path: logs/monitor.log
